"""Export a local, self-contained replay of a recorded tool investigation."""
import json
from pathlib import Path


def export_replay(trace: dict, output: Path) -> None:
    """Write a saved replay; observations/model strings are data, never HTML/code."""
    if trace.get('schema_version') != 1 or not isinstance(trace.get('events'), list):
        raise ValueError('schema_version=1 and an events list are required')
    payload = json.dumps(trace, ensure_ascii=True, allow_nan=False, separators=(',', ':'))
    # An HTML raw-text script element ends at </script> even for application/json.
    payload = payload.replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    Path(output).write_text(_HTML.replace('__TRACE_JSON__', payload), encoding='utf-8')


_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tool laboratory · saved replay</title>
<style>
:root{color-scheme:light;--ink:#172735;--muted:#586776;--line:#d8e0e6;--accent:#126d78}*{box-sizing:border-box}body{margin:0;background:#f2f5f7;color:var(--ink);font:15px/1.5 system-ui,sans-serif}main{max-width:1300px;margin:auto;padding:24px}h1{font-size:26px;margin:0}h2{font-size:17px;margin:0 0 12px}h3{font-size:14px;margin:18px 0 8px}p{margin:6px 0 14px}.muted,small{color:var(--muted)}.badge{display:inline-block;background:#e4eff1;color:#14545e;padding:3px 9px;border-radius:5px;font-size:12px}.controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:20px 0}button,select{font:inherit;border:1px solid #b6c5cd;border-radius:6px;padding:7px 12px;background:white;color:var(--ink)}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #2598aa;outline-offset:2px}button:disabled{opacity:.45}input[type=range]{flex:1;min-width:150px;accent-color:var(--accent)}.grid{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(0,1fr);gap:16px}.card{background:white;border:1px solid var(--line);border-radius:10px;padding:18px;min-width:0}.wide{grid-column:1/-1}svg{width:100%;height:auto;background:#fafcfd;border:1px solid #e5ebef;border-radius:6px}.legend{display:flex;gap:16px;font-size:12px;color:var(--muted);flex-wrap:wrap}.dot{display:inline-block;width:10px;height:10px;border-radius:50%;background:#126d78;margin-right:5px}.pred{background:#d07925}.tablescroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{padding:8px;text-align:left;vertical-align:top;border-bottom:1px solid #e4eaee}th{color:var(--muted);font-weight:600}td.formula{font:12px/1.5 ui-monospace,monospace;overflow-wrap:anywhere;min-width:180px}.facts{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fact{background:#f2f6f8;padding:8px;border-radius:5px}.fact small{display:block}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.5 ui-monospace,monospace}details{margin-top:12px}summary{cursor:pointer;color:var(--accent)}.revision{padding:8px;background:#f5f7f9;border-left:3px solid #a8bdc8;white-space:pre-wrap;overflow-wrap:anywhere}#empty{padding:20px;color:var(--muted)}@media(max-width:800px){main{padding:14px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}h1{font-size:22px}.card{padding:14px}}
</style></head><body><main>
<header><span class="badge">Saved replay · no live training</span><h1>The tool laboratory</h1>
<p class="muted">Recorded actions, predictions and model changes. Model scores are heuristic, not calibrated uncertainty. Expressions use a supplied grammar; this replay makes no true-law claim.</p><p id="run-meta"></p></header>
<div class="controls"><button id="previous" aria-label="Previous recorded action">←</button><button id="play">Play</button><button id="next" aria-label="Next recorded action">→</button><input id="slider" type="range" min="0" value="0" aria-label="Recorded action"><label>Speed <select id="speed"><option value="1200">Slow</option><option value="650" selected>Normal</option><option value="250">Fast</option></select></label><span id="position" aria-live="polite"></span></div>
<div id="empty" hidden>No recorded actions. Final models and any evaluator notes are shown below.</div>
<div class="grid"><section class="card"><h2>Observed trajectory</h2><svg id="plot" viewBox="0 0 620 400" role="img" aria-label="Observed positions and next-position predictions"></svg><div class="legend"><span><i class="dot"></i>Recorded positions</span><span><i class="dot pred"></i>Predicted outcome</span><span>Square: position before action</span></div><p class="muted"><small>Coordinates are recorded sensor readings. The path connects readings; it does not reconstruct unobserved motion. Axes include recorded outcomes and the displayed predictions.</small></p></section>
<section class="card"><h2 id="action-title">Action</h2><div class="facts" id="facts"></div><h3>Recorded selection reason</h3><p id="reason"></p><p id="noise-note" class="muted"></p><h3>Model revisions after this outcome</h3><div id="revision" class="revision"></div></section>
<section class="card wide"><h2>Predictions made before the outcome</h2><div class="tablescroll"><table><thead><tr><th>Model</th><th>Formula at prediction</th><th>Predicted x, y</th><th>Recorded squared error</th></tr></thead><tbody id="predictions"></tbody></table></div><p id="actual" class="muted"></p></section>
<section class="card"><h2>Models after the outcome</h2><div class="tablescroll"><table><thead><tr><th>Model / formula</th><th>Prequential MSE</th><th>Past prediction count</th></tr></thead><tbody id="models"></tbody></table></div><p class="muted"><small>Prequential MSE scores the structure and refitting procedure over the recent 12 events. It does not validate the current coefficients or provide calibrated uncertainty. Newly proposed models may have little or no fresh evidence.</small></p></section>
<section class="card"><h2>Planner alternatives before the action</h2><p id="selected-score" class="muted"></p><div class="tablescroll"><table><thead><tr><th>Action</th><th>Score</th><th>Disagreement</th><th>Coverage</th></tr></thead><tbody id="options"></tbody></table></div><details><summary>Alternative model predictions</summary><pre id="option-predictions"></pre></details></section>
<section class="card wide"><details><summary>Final models and independent evaluator notes</summary><p class="muted">End-of-run context, separate from the displayed action. Evaluator outcomes are not presented as inputs to the planner.</p><pre id="final"></pre></details></section></div>
</main><script id="trace-data" type="application/json">__TRACE_JSON__</script>
<script>
'use strict';
const trace=JSON.parse(document.getElementById('trace-data').textContent),events=trace.events;
const $=id=>document.getElementById(id), put=(id,value)=>{$(id).textContent=value;};
const show=value=>value===null||value===undefined?'—':typeof value==='string'?value:JSON.stringify(value);
const number=value=>typeof value==='number'&&Number.isFinite(value)?Number(value.toPrecision(5)).toString():'—';
const action=a=>{if(!a)return '—';let s=show(a.kind);if(a.angle!==undefined)s+=' · angle '+number(a.angle);if(a.magnitude!==undefined)s+=' · magnitude '+number(a.magnitude);if(a.ticks!==undefined)s+=' · ticks '+show(a.ticks);return s;};
function row(parent,values,formulaIndex=-1){const tr=document.createElement('tr');values.forEach((v,i)=>{const td=document.createElement('td');td.textContent=show(v);if(i===formulaIndex)td.className='formula';tr.appendChild(td);});parent.appendChild(tr);}
function fact(label,value){const box=document.createElement('div');box.className='fact';const small=document.createElement('small');small.textContent=label;const text=document.createElement('span');text.textContent=show(value);box.append(small,text);$('facts').appendChild(box);}
const finitePoint=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y);
function draw(index,event){const svg=$('plot');svg.replaceChildren();const pts=[];events.slice(0,index+1).forEach(e=>{if(finitePoint(e.before))pts.push(e.before);if(finitePoint(e.after))pts.push(e.after);});const predictions=(event.predictions||[]).filter(finitePoint);const all=pts.concat(predictions);if(!all.length)return;
const xs=all.map(p=>p.x),ys=all.map(p=>p.y);let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const dx=Math.max(maxX-minX,.2),dy=Math.max(maxY-minY,.2);minX-=dx*.12;maxX+=dx*.12;minY-=dy*.12;maxY+=dy*.12;const X=x=>54+(x-minX)/(maxX-minX)*542,Y=y=>355-(y-minY)/(maxY-minY)*325;
function node(tag,attrs,text){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));if(text!==undefined)n.textContent=text;svg.appendChild(n);return n;}
for(let i=0;i<=4;i++){const x=minX+(maxX-minX)*i/4,y=minY+(maxY-minY)*i/4;node('line',{x1:X(x),y1:30,x2:X(x),y2:355,stroke:'#e1e9ee'});node('line',{x1:54,y1:Y(y),x2:596,y2:Y(y),stroke:'#e1e9ee'});node('text',{x:X(x),y:375,'text-anchor':'middle','font-size':11,fill:'#586776'},number(x));node('text',{x:47,y:Y(y)+4,'text-anchor':'end','font-size':11,fill:'#586776'},number(y));}
node('text',{x:610,y:375,'font-size':12},'x');node('text',{x:18,y:20,'font-size':12},'y');node('polyline',{points:pts.map(p=>X(p.x)+','+Y(p.y)).join(' '),fill:'none',stroke:'#126d78','stroke-width':2});
predictions.forEach(p=>{const n=node('circle',{cx:X(p.x),cy:Y(p.y),r:6,fill:'#d07925',opacity:.75});const title=document.createElementNS(n.namespaceURI,'title');title.textContent=show(p.model_id)+': '+number(p.x)+', '+number(p.y);n.appendChild(title);});
if(finitePoint(event.before))node('rect',{x:X(event.before.x)-5,y:Y(event.before.y)-5,width:10,height:10,fill:'#53616c'});if(finitePoint(event.after))node('circle',{cx:X(event.after.x),cy:Y(event.after.y),r:6,fill:'#126d78',stroke:'white','stroke-width':2});}
let index=0,timer=null;
function pause(){if(timer!==null)clearInterval(timer);timer=null;put('play','Play');}
function render(){const e=events[index]||{},choice=e.choice||{};put('position',events.length?(index+1)+' / '+events.length:'0 / 0');$('slider').value=index;put('action-title','Action '+show(e.step===undefined?index+1:e.step)+' · '+action(e.action));$('facts').replaceChildren();fact('Tick before → after',show(e.before?.tick)+' → '+show(e.after?.tick));fact('Action cost / total',show(e.cost)+' / '+show(e.total_cost));fact('Observed before',number(e.before?.x)+', '+number(e.before?.y));fact('Observed after',number(e.after?.x)+', '+number(e.after?.y));put('reason',choice.reason||'No selection rationale recorded.');put('noise-note',[choice.noise_limit===undefined?null:'Noise limitation: '+show(choice.noise_limit),choice.sensor_noise_variance_estimate===undefined?null:'Sensor noise variance estimate: '+number(choice.sensor_noise_variance_estimate),choice.home_readings===undefined?null:'Home readings: '+show(choice.home_readings)].filter(v=>v!==null).join(' · '));put('selected-score','Selected heuristic score: '+number(choice.selected_score));put('revision',JSON.stringify(e.revision||{added:[],removed:[],updated:[]},null,2));
$('predictions').replaceChildren();const errors=new Map((e.errors||[]).map(v=>[v.model_id,v.squared_error]));(e.predictions||[]).forEach(v=>row($('predictions'),[v.model_id,v.formula,number(v.x)+', '+number(v.y),number(errors.get(v.model_id))],1));put('actual','Actual recorded outcome: x '+number(e.after?.x)+', y '+number(e.after?.y));
$('models').replaceChildren();(e.models_after||(!events.length?trace.final_models:[])||[]).forEach(m=>row($('models'),[show(m.id)+' · '+show(m.formula),number(m.prequential_mse),m.validated_predictions],0));$('options').replaceChildren();(choice.options||[]).forEach(o=>row($('options'),[action(o.action),number(o.score),number(o.disagreement),number(o.coverage)]));put('option-predictions',JSON.stringify((choice.options||[]).map(o=>({action:o.action,predictions:o.predictions||[]})),null,2));draw(index,e);$('previous').disabled=!events.length||index===0;$('next').disabled=!events.length||index===events.length-1;}
put('run-meta','Policy: '+show(trace.policy)+' · Variant: '+show(trace.variant)+' · Seed: '+show(trace.seed)+' · Status: '+show(trace.status));put('final',JSON.stringify({final_models:trace.final_models||[],evaluation:trace.evaluation||null},null,2));$('slider').max=Math.max(0,events.length-1);$('slider').disabled=!events.length;$('play').disabled=!events.length;$('empty').hidden=!!events.length;
$('previous').onclick=()=>{pause();index=Math.max(0,index-1);render();};$('next').onclick=()=>{pause();index=Math.min(events.length-1,index+1);render();};$('slider').oninput=()=>{pause();index=Number($('slider').value);render();};$('play').onclick=()=>{if(timer!==null){pause();return;}if(index>=events.length-1)index=0;render();put('play','Pause');timer=setInterval(()=>{if(index>=events.length-1){pause();return;}index++;render();},Number($('speed').value));};$('speed').onchange=pause;document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});render();
</script></body></html>'''
