"""Self-contained saved replay of recorded assumption-revision decisions."""
import json
from pathlib import Path


def replay(trace):
    if not isinstance(trace.get('events'),list):
        raise ValueError('events list required')
    trace=dict(trace, replay_views=[event_view(trace,i) for i in range(len(trace['events']))])
    payload=json.dumps(trace,ensure_ascii=True,allow_nan=False,separators=(',',':'))
    for char,escaped in [('<','\\u003c'),('>','\\u003e'),('&','\\u0026')]:
        payload=payload.replace(char,escaped)
    return _HTML.replace('__DATA__',payload)


def event_view(trace,index):
    """Only event-prefix evidence; full prospective tapes were already recorded."""
    event=trace['events'][index]
    cycle_id=event.get('cycle_id')
    revision=event.get('revision') or {}
    if cycle_id is None:
        cycle_id=revision.get('started_cycle',revision.get('cycle_id'))
    screening=None
    plan=event.get('confirmation_plan')
    for earlier in trace['events'][:index+1]:
        change=earlier.get('revision') or {}
        earlier_id=earlier.get('cycle_id')
        if earlier_id is None:
            earlier_id=change.get('started_cycle',change.get('cycle_id',change.get('id')))
        if cycle_id is not None and earlier_id==cycle_id:
            if change.get('screening') is not None:
                screening=change['screening']
            if change.get('confirmation_plan') is not None:
                plan=change['confirmation_plan']
    completed=None
    for cycle in trace.get('cycles',[]):
        steps=cycle.get('check_steps') or []
        if cycle.get('id')==cycle_id and steps and event.get('step',-1)>=max(steps):
            completed=cycle
    long_tape=event.get('prediction_origin')=='confirmation_start_frozen_tape'
    return dict(screening=screening,completed=completed,confirmation_plan=plan,
                prediction_origin=(plan.get('start') if plan else None) if long_tape else event.get('before'),
                plot_predictions=(plan.get('predictions',[]) if plan else []) if long_tape else event.get('predictions',[]),
                continuous_confirmation=long_tape,
                origin_missing=bool(long_tape and not plan))


def export_replay(trace,path):
    Path(path).write_text(replay(trace),encoding='utf-8')


_HTML=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Assumption revision · saved investigation</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f5f7;color:#20313e;font:15px/1.5 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:24px}h1{font-size:26px;margin:8px 0}h2{font-size:18px;margin:0 0 12px}p{margin:8px 0}.muted{color:#596a76}.tag{background:#deebee;color:#165363;border-radius:5px;padding:4px 9px;font-size:12px}.controls{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:20px 0}button{font:inherit;padding:8px 14px;background:white;border:1px solid #b8c6ce;border-radius:6px;color:inherit}button:disabled{opacity:.4}button:focus-visible,input:focus-visible{outline:3px solid #318b9a;outline-offset:2px}input{flex:1;min-width:140px;accent-color:#167784}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{padding:18px;background:white;border:1px solid #d9e2e7;border-radius:10px;min-width:0}.wide{grid-column:1/-1}svg{width:100%;height:auto;background:#fafcfd;border:1px solid #e4eaf0;border-radius:5px}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;vertical-align:top;padding:8px;border-bottom:1px solid #e1e8ec}th{color:#596a76}.scroll{overflow:auto}.formula{font-family:ui-monospace,monospace;overflow-wrap:anywhere}pre{font:12px/1.5 ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere}summary{color:#156275;cursor:pointer}details{margin-top:12px}.decision{padding:12px;background:#eef4f5;border-left:3px solid #398391}@media(max-width:750px){main{padding:14px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.card{padding:14px}}
</style></head><body><main><span class="tag">Saved replay · not live learning</span><h1>Failure → alternatives → test → revision</h1><p class="muted">Recorded predictions and decisions within a supplied grammar. Disagreement scores and adoption margins are heuristics, not calibrated confidence or proof of a true law. No rationale is inferred after the event.</p><p id="metadata"></p><p id="status" class="decision"></p>
<div class="controls"><button id="prev" aria-label="Previous experiment">←</button><button id="play">Play</button><button id="next" aria-label="Next experiment">→</button><input id="slider" type="range" min="0" value="0" aria-label="Recorded experiment"><span id="step" aria-live="polite"></span></div>
<div class="grid"><section class="card"><h2>Observed trajectory and frozen prediction tapes</h2><svg id="plot" viewBox="0 0 600 390" role="img" aria-label="Recorded trajectory with frozen prediction tapes"></svg><p class="muted">Teal: observed readings. Colored dashed paths: frozen prospective predictions. Continuous confirmation shows the full eight-action tape from its original start, including predictions beyond the displayed observation. Lines connect readings; unobserved motion is not reconstructed.</p></section>
<section class="card"><h2 id="heading">Experiment</h2><p id="actions"></p><p id="reason"></p><p id="threshold" class="muted"></p><p id="prediction-origin" class="decision"></p><h2>Incumbent before this experiment</h2><p id="old" class="formula"></p><h2>Retained model after this experiment</h2><p id="after" class="formula"></p></section>
<section class="card wide"><h2>Prospective alternatives and observed errors</h2><div class="scroll"><table><thead><tr><th>Model</th><th>Frozen formula</th><th>Predicted tape</th><th>Recorded experiment loss</th></tr></thead><tbody id="models"></tbody></table></div><p id="outcomes" class="muted"></p></section>
<section class="card"><h2>Action choices before execution</h2><div class="scroll"><table><thead><tr><th>Option / actions</th><th>Disagreement</th><th>Coverage</th><th>Score</th></tr></thead><tbody id="options"></tbody></table></div><details><summary>Raw prospective options and prediction tapes</summary><pre id="raw-options"></pre></details></section>
<section class="card"><h2>Revision cycle</h2><p id="cycle-status" class="decision"></p><p id="trigger"></p><p id="screening"></p><p id="confirmation"></p><div class="scroll"><table><thead><tr><th>Frozen model</th><th>Decision-batch mean loss</th></tr></thead><tbody id="cycle-losses"></tbody></table></div><p id="margin"></p><details><summary>Recorded trigger, proposal work and cycle decision</summary><pre id="raw-cycle"></pre></details></section>
<section class="card wide"><details><summary>End-of-run model and independent evaluation</summary><p class="muted">Final context, separate from the current event. Evaluation outcomes do not guide adoption.</p><pre id="final"></pre></details></section></div></main>
<script id="trace-data" type="application/json">__DATA__</script><script>
'use strict';const trace=JSON.parse(document.getElementById('trace-data').textContent),events=trace.events;const $=id=>document.getElementById(id),put=(id,v)=>{$(id).textContent=v;};const show=v=>v===null||v===undefined?'—':typeof v==='string'?v:JSON.stringify(v);const num=v=>typeof v==='number'&&Number.isFinite(v)?Number(v.toPrecision(5)).toString():'—';const actions=values=>(values||[]).map(a=>show(a.kind)+(a.kind==='push'?'('+num(a.angle)+', '+num(a.magnitude)+')':a.kind==='wait'?'('+show(a.ticks)+')':'')).join(' → ');
function row(id,values){const tr=document.createElement('tr');values.forEach(value=>{const td=document.createElement('td');td.textContent=show(value);tr.appendChild(td);});$(id).appendChild(tr);}
const point=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y);const colors=['#bc6331','#7760a8','#b94d77','#517e38'];
function draw(index,event){const svg=$('plot');svg.replaceChildren();const history=[];events.slice(0,index+1).forEach(e=>{if(point(e.before))history.push(e.before);(e.outcomes||[]).filter(point).forEach(p=>history.push(p));});const view=trace.replay_views[index]||{};const tapes=(view.plot_predictions||event.predictions||[]).map(p=>({id:p.model_id,points:(p.tape||[]).map(pair=>({x:pair[0],y:pair[1]})).filter(point)}));const all=history.concat(point(view.prediction_origin)?[view.prediction_origin]:[],...tapes.map(t=>t.points));if(!all.length)return;let loX=Math.min(...all.map(p=>p.x)),hiX=Math.max(...all.map(p=>p.x)),loY=Math.min(...all.map(p=>p.y)),hiY=Math.max(...all.map(p=>p.y));let dx=Math.max(.2,hiX-loX),dy=Math.max(.2,hiY-loY);loX-=dx*.1;hiX+=dx*.1;loY-=dy*.1;hiY+=dy*.1;const X=x=>55+(x-loX)/(hiX-loX)*520,Y=y=>345-(y-loY)/(hiY-loY)*315;function node(tag,attrs,text){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));if(text!==undefined)n.textContent=text;svg.appendChild(n);return n;}
for(let i=0;i<=4;i++){let x=loX+(hiX-loX)*i/4,y=loY+(hiY-loY)*i/4;node('line',{x1:X(x),x2:X(x),y1:30,y2:345,stroke:'#e1e8ec'});node('line',{x1:55,x2:575,y1:Y(y),y2:Y(y),stroke:'#e1e8ec'});node('text',{x:X(x),y:366,'text-anchor':'middle','font-size':11},num(x));node('text',{x:48,y:Y(y)+4,'text-anchor':'end','font-size':11},num(y));}node('polyline',{points:history.map(p=>X(p.x)+','+Y(p.y)).join(' '),fill:'none',stroke:'#197785','stroke-width':2});tapes.forEach((t,i)=>{const points=(point(view.prediction_origin)?[view.prediction_origin]:[]).concat(t.points);node('polyline',{points:points.map(p=>X(p.x)+','+Y(p.y)).join(' '),fill:'none',stroke:colors[i%colors.length],'stroke-width':2,'stroke-dasharray':'5 4'});t.points.forEach(p=>{const n=node('circle',{cx:X(p.x),cy:Y(p.y),r:4,fill:colors[i%colors.length]});const title=document.createElementNS(n.namespaceURI,'title');title.textContent=show(t.id);n.appendChild(title);});});(event.outcomes||[]).filter(point).forEach(p=>node('circle',{cx:X(p.x),cy:Y(p.y),r:5,fill:'#197785',stroke:'white'}));}
let index=0,timer=null;function pause(){clearInterval(timer);timer=null;put('play','Play');}
function render(){const e=events[index]||{},view=trace.replay_views[index]||{};put('step',events.length?(index+1)+' / '+events.length:'No recorded experiments');$('slider').value=index;put('heading','Experiment '+show(e.step)+' · '+show(e.check_stage||e.phase)+' · rule '+show(e.check_rule||trace.check_rule||'original'));put('actions',actions(e.actions));put('reason','Recorded choice reason: '+show(e.reason));put('threshold','Failure threshold: '+num(e.failure_threshold)+' · fixed home variance: '+num(e.home_variance));put('prediction-origin',view.origin_missing?'Continuous confirmation origin not recorded; prediction paths are omitted rather than restarted from the current observation.':view.continuous_confirmation?'Continuous eight-action confirmation tape from tick '+show(view.prediction_origin?.tick)+'. Current scored slice: positions '+show((e.confirmation_offset||0)+1)+'–'+show((e.confirmation_offset||0)+2)+'. Intermediate observed states do not restart these predictions.':'Predictions start from the current observed state; this experiment is locally restarted.');const models=e.models||[];const incumbent=models.find(m=>m.id===e.incumbent_id);put('old',incumbent?show(incumbent.formula):show(e.incumbent_id));put('after',show(e.incumbent_after?.formula));$('models').replaceChildren();models.forEach(m=>{const prediction=(e.predictions||[]).find(p=>p.model_id===m.id);row('models',[m.id,m.formula,show(prediction?.tape),num(e.losses?.[m.id])]);});put('outcomes','Recorded outcomes: '+show(e.outcomes));$('options').replaceChildren();(e.options||[]).forEach(o=>row('options',[(o.index===e.chosen?'Chosen · ':'')+show(o.index)+' · '+actions(o.actions),num(o.disagreement),num(o.coverage),num(o.score)]));put('raw-options',JSON.stringify(e.options||[],null,2));
const cycleId=e.cycle_id??e.revision?.started_cycle;const cycle=view.completed;const trigger=e.revision?.trigger||cycle?.trigger;put('trigger',trigger?'Recorded failure trigger: '+show(trigger):'No new trigger recorded at this event.');$('cycle-losses').replaceChildren();const screening=view.screening||cycle?.screening;put('screening',screening?'Screening winner: '+show(screening.winner_id)+' · required margin: '+num(screening.required_margin)+' · passed margin: '+show(screening.passed)+' · mean losses: '+show(screening.mean_squared_error):'Screening result not yet recorded.');put('confirmation',cycle?.confirmation_mean_squared_error?'Confirmation mean losses: '+show(cycle.confirmation_mean_squared_error)+' · required margin: '+num(cycle.confirmation_required_margin)+' · passed: '+show(cycle.confirmation_passed):'Confirmation result not yet available.');if(cycle){put('cycle-status',cycle.accepted?'Accepted alternative: '+show(cycle.selected_id):'Kept incumbent; the candidate did not meet the recorded adoption rule.');Object.entries(cycle.mean_squared_error||{}).forEach(([id,loss])=>row('cycle-losses',[id,num(loss)]));put('margin','Decision candidate: '+show(cycle.best_alternative)+' · required improvement: '+num(cycle.required_margin)+' · pooled mean losses: '+show(cycle.pooled_mean_squared_error));}else{put('cycle-status',cycleId!==null&&cycleId!==undefined?'Check in progress; final decision not yet available at this step.':'No active revision cycle.');put('margin','');}put('raw-cycle',JSON.stringify({event_revision:e.revision||null,screening:screening||null,prospective_confirmation_plan:view.confirmation_plan||null,completed_cycle:cycle||null},null,2));draw(index,e);$('prev').disabled=!events.length||index===0;$('next').disabled=!events.length||index===events.length-1;}
put('metadata','Policy: '+show(trace.policy)+' · Rule: '+show(trace.check_rule||'original')+' · Variant: '+show(trace.variant)+' · Seed: '+show(trace.seed));put('status','End-of-run explanation status: '+show(trace.explanation_status)+((trace.cycles||[]).length?'':' · No revision cycles recorded; this does not establish that the model is correct.'));put('final',JSON.stringify({selected_model:trace.selected_model||null,evaluation:trace.evaluation||null},null,2));$('slider').max=Math.max(0,events.length-1);$('slider').disabled=!events.length;$('play').disabled=!events.length;$('prev').onclick=()=>{pause();index=Math.max(0,index-1);render();};$('next').onclick=()=>{pause();index=Math.min(events.length-1,index+1);render();};$('slider').oninput=()=>{pause();index=Number($('slider').value);render();};$('play').onclick=()=>{if(timer!==null){pause();return;}if(index>=events.length-1)index=0;render();put('play','Pause');timer=setInterval(()=>{if(index>=events.length-1){pause();return;}index++;render();},850);};document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});render();
</script></body></html>'''
